name: Fundamental Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: npm install
    - name: Run type checks
      run: npm run check
    - name: Build
      run: npm run build
    - name: Run lint
      run: npm run lint
    - name: Run tests
      run: npm run test
